// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gN7sHGIcdqJWvyRNOhduWcu4RikBqUI',
    appId: '1:89093480155:web:c34952f32fa609ab5ef6fe',
    messagingSenderId: '89093480155',
    projectId: 'appmobile-79773',
    authDomain: 'appmobile-79773.firebaseapp.com',
    databaseURL: 'https://appmobile-79773-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-79773.appspot.com',
    measurementId: 'G-NBGLHRGN7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9drXmz89vIGLMtwyzUhu5b6DE43ClGA',
    appId: '1:89093480155:android:3060e00cf42a03445ef6fe',
    messagingSenderId: '89093480155',
    projectId: 'appmobile-79773',
    databaseURL: 'https://appmobile-79773-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-79773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbbd5ICH1A_G0WqDfdF157q9E193iLw4',
    appId: '1:89093480155:ios:7eaeeed367c948ef5ef6fe',
    messagingSenderId: '89093480155',
    projectId: 'appmobile-79773',
    databaseURL: 'https://appmobile-79773-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-79773.appspot.com',
    iosClientId: '89093480155-fgl9pe7tid2n7a9h33abrhe9lq82em4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.all4my',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbbd5ICH1A_G0WqDfdF157q9E193iLw4',
    appId: '1:89093480155:ios:7eaeeed367c948ef5ef6fe',
    messagingSenderId: '89093480155',
    projectId: 'appmobile-79773',
    databaseURL: 'https://appmobile-79773-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-79773.appspot.com',
    iosClientId: '89093480155-fgl9pe7tid2n7a9h33abrhe9lq82em4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.all4my',
  );
}
